### ISSUE TITLE
Libraries like Message bus, MPP and GatewayLib should be deployed once per chain

### ISSUE THREAD

**Issue by sarvesh-ost** [OpenST/mosaic-chains#56]
As a chain owner, 
When I set up a new auxiliary chain, 
It should be possible to use already deployed libraries on origin chain so that chain setup gas cost can be reduced.

**Comment by schemar** [comment]
### Story
As a chain owner
I want to re-use existing library contracts on origin
Because that saves me gas costs
And potentially adds trust.

### Scenario
Given that library contracts have been deployed to origin before
When I create a new auxiliary chain
Then it should re-use the existing library contracts on origin.

**Comment by benjaminbollen** [comment]
valid, but lower priority

**Comment by schemar** [comment]
As part of this ticket, move the code that deploys the libraries on origin into a separate command that can be run first if required (new origin).
The addresses should be stored and made available through the mosaic config.

**Comment by schemar** [comment]
This ticket requires a mosaic config, right? Is there a ticket for that?
/cc @deepesh-kn

**Comment by sarvesh-ost** [comment]
I created a small PR to add mosaic-config. Refer #76
