### ISSUE TITLE
Deploy subgraph (script)

### ISSUE THREAD

**Issue by deepesh-kn** [OpenST/mosaic-chains#87]
deploy subgraph (script)

- run codegen; needs subgraph.yaml.
- create-local command.
- deploy-local command.

**Comment by sarvesh-ost** [comment]
In ticket #86, subgraph projects are added for the origin and auxiliary chain. Instead of file subgraph.yaml these projects contain subgraph.yaml.mustache. During the deployment, the template variable should be replaced with actual contract addresses available in the mosaic config. 

You can read about mustache template from [here](https://www.npmjs.com/package/mustache)

After this ticket, the flow of `mosaic start` will change to below:
1. Runs the mosaic chain as per the current flow
2. If the graph project doesn't exist in folder `~/.mosaic/{chainId}/graph`, create a graph project.
 During graph creation, the mushtache template for file `subgraph.yaml.mustache` should be replaced with actual addresses using the mosaic config and a new file should be created `subgraph.yaml`. 
3. if the project is available in `~/.mosaic/{chainId}/graph` folder, check if subgraph is not already deployed, if not deploy the subgraph which is a two-step process: 
   1. Create local 
   2. Deploy local

**Comment by puneet-khushwani-eth** [comment]
Deploying sub graph for origin would need value of `eip20GatewayAddress` which can't be determined unless given an aux chain id. As `mosaic start` command does not take this info as an argument, we feel that these deployments can not be a part of  `mosaic start`.

We are proposing a new command

`./mosaic deploy-sub-graph --aux-chain 1407 --subGraph-type origin --graphAdminRpc http://localhost:12121 --graphIpfs http://localhost:23232`

`./mosaic deploy-sub-graph --aux-chain 1407 --subGraph-type auxiliary --graphAdminRpc http://localhost:12121 --graphIpfs http://localhost:23232`

**Comment by puneet-khushwani-eth** [comment]
As discussed here, we would also in `mosaic start` start copying over all the mosaic config files found in the repo to `./mosaic/`. 

This would enable us to use `Mosaic.from()` to fetch relevant addresses.

**Comment by sarvesh-ost** [comment]
ABIs copied by `graph init` are potentially duplicate. 
Refer https://github.com/OpenST/mosaic-chains/pull/93#discussion_r293302535

It would we nice if we can evaluate in this ticket that they are actually duplicate.

**Comment by benjaminbollen** [comment]
> Deploying sub graph for origin would need value of eip20GatewayAddress which can't be determined unless given an aux chain id. As mosaic start command does not take this info as an argument, we feel that these deployments can not be a part of mosaic start.

a different question to ask is, given starting an auxiliary chain, can we add the subgraph (anchor, gateway) on an existing graph-node (assumed, already running) for this origin chain?

**Comment by benjaminbollen** [comment]
so on 

`mosaic start ropsten` -> start subgraph of origin part of `1407` and `1406`
`mosaic start ethereum` -> start subgraph of origin part of `1414`
`mosaic start 14xx` -> start subgraph of auxiliary part of `14xx`

**Comment by benjaminbollen** [comment]
Im fine with the templating suggested by @sarvesh-ost in the previous ticket #93 

however, the tickets were always for *explicit* subgraphs for the chains we have, 1406, 1407, 1414; from this perspective it s quite clear

**Comment by benjaminbollen** [comment]
so to be clear, we dont need an explicit command, or to deviate from the specification we all agreed on
